plugins {
    id 'java'
    id 'com.gradleup.shadow' version '9.3.0'
    id 'maven-publish'
}

group = 'nebulice.hamster.hashGui'
version = 'R0.2.0-SNAPSHOT'

def hashrc = '/home/blegourr/dev/nebulice/Hamster/PLUGIN/libs/hamster-hashgui/build_plugin'
def libsFolder = 'libs'

repositories {
    mavenCentral()
    maven { url = uri('https://repo.alessiodp.com/releases/') }
    maven {
        name = "papermc"
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }
    maven {
        name = "sonatype"
        url = "https://oss.sonatype.org/content/groups/public/"
    }
    maven {
        name = "minecraft-repo"
        url = "https://libraries.minecraft.net/"
    }
}

configurations {
    implementation.canBeResolved = true
}

dependencies {
    compileOnly "io.papermc.paper:paper-api:26.1.2.build.+"
    compileOnly 'com.mojang:authlib:1.5.21'

    implementation fileTree(dir: libsFolder, include: ['*.jar'])
}

def targetJavaVersion = 25

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
}
tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release.set(targetJavaVersion)
    options.compilerArgs += ['-Xlint:deprecation']
}

processResources {
    def props = [
            name   : rootProject.name,
            version: version
    ]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('plugin.yml') {
        expand props
    }
}

shadowJar {
    dependencies {
        exclude(dependency('io.papermc.paper:paper-api:26.1.2.build.+'))
        exclude(dependency('com.mojang:authlib:1.5.21'))
    }

    archiveClassifier.set('')

    mergeServiceFiles()
    minimize()
}

tasks.register('make', Copy) {
    dependsOn shadowJar

    from('build/libs')
    into hashrc
    include '*.jar'
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId = group
            artifactId = rootProject.name
            version = version

            from components.java
        }
    }
}
