name: 🐳 Build & Push Plugin (hamster-hashgui)

on:
  push:
    branches:
      - main
      - integration
      - integrations
      - dev
      - 'refactor/*'
      - 'feat/*'
  repository_dispatch:
    types: [dependency_updated, build-plugin]
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: Nebulice/Hamster-docker/.github/workflows/reusable-plugin-ci.yml@dev
    with:
      plugin_id: 'hamster-plugin-hashgui'
      plugin_name: 'hamster-hashgui'
      jar_name: 'Hamster-Hashgui.jar'
      depends_on: ''
      triggers_downstream: 'Hamster-Utility,Hamster-Core,Hamster-Core-velocity,Hamster-Whitelist,Hamster-Lore,Hamster-sync,Hamster-Economie,Hamster-Head,Hamster-Connect,Hamster-ServerManager,Hamster-Starter,Hamster-ServerSwitch,Hamster-Houses,Hamster-DisplayStat,Hamster-VelocityReconnect,Hamster-VelocityRoutes'
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
